"""Add agent credentials and heartbeat state

Revision ID: 5ab642aedfa6
Revises: c00f8d6a516a
Create Date: 2026-07-17 18:05:18.447177
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '5ab642aedfa6'
down_revision: str | None = 'c00f8d6a516a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('token_prefix', sa.String(length=32), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_credentials_agent_id'), 'agent_credentials', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_credentials_token_prefix'), 'agent_credentials', ['token_prefix'], unique=True)
    op.add_column('agents', sa.Column('runtime', sa.String(length=100), nullable=True))
    op.add_column('agents', sa.Column('runtime_version', sa.String(length=100), nullable=True))
    op.add_column(
        "agents",
        sa.Column(
            "heartbeat_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column(
        "agents",
        "heartbeat_metadata",
        server_default=None,
    )
    op.add_column('agents', sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_agents_is_enabled'), 'agents', ['is_enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_is_enabled'), table_name='agents')
    op.drop_column('agents', 'is_enabled')
    op.drop_column('agents', 'heartbeat_metadata')
    op.drop_column('agents', 'runtime_version')
    op.drop_column('agents', 'runtime')
    op.drop_index(op.f('ix_agent_credentials_token_prefix'), table_name='agent_credentials')
    op.drop_index(op.f('ix_agent_credentials_agent_id'), table_name='agent_credentials')
    op.drop_table('agent_credentials')
    # ### end Alembic commands ###
