from fastapi import FastAPI

from app.api.routes import (
    agent_context_router,
    agent_context_runtime_router,
    agent_fleet_router,
    agent_governance_router,
    agent_notes_router,
    agent_packages_router,
    agent_proposals_router,
    agent_research_router,
    agent_runtime_router,
    agents_router,
    alpha_campaign_router,
    authority_router,
    autonomous_research_router,
    calibrations_router,
    causal_pipelines_router,
    channel_conversations_router,
    controls_router,
    conversations_router,
    corpus_router,
    corpus_sync_router,
    curriculum_router,
    data_contracts_router,
    derived_state_router,
    discovery_portfolio_router,
    discovery_router,
    evaluator_routing_router,
    evidence_router,
    execution_calibration_schemas_router,
    execution_event_schemas_router,
    factor_language_router,
    falsification_router,
    fleet_router,
    founder_channel_router,
    governance_audit_router,
    governance_router,
    graph_router,
    health_router,
    ingestion_recovery_router,
    ingestion_router,
    institutional_lifecycle_router,
    intelligence_evaluation_router,
    laboratory_router,
    lake_operations_router,
    lifecycle_consequence_router,
    lifecycle_router,
    market_data_catalog_router,
    memory_router,
    metrics_router,
    microstructure_models_router,
    missions_router,
    model_evaluations_router,
    observability_router,
    off_policy_router,
    offline_rl_router,
    oms_schemas_router,
    operational_notes_router,
    operations_router,
    packages_router,
    platform_router,
    portfolio_capacity_schemas_router,
    portfolio_solvers_router,
    prompt_policies_router,
    proposals_router,
    quantitative_receipts_router,
    reference_data_router,
    research_bridge_router,
    research_programs_router,
    research_router,
    retrieval_router,
    risk_budget_schemas_router,
    risk_rules_router,
    risk_stress_router,
    runbook_packages_router,
    scientific_fidelity_router,
    selection_audit_router,
    statistical_search_router,
    supervisor_router,
    surveillance_router,
    symbolic_search_router,
    task_graphs_router,
    task_runtime_router,
    tasks_router,
    venue_identities_router,
    workload_identities_router,
)
from app.core.config import get_settings

settings = get_settings()

app = FastAPI(
    title=settings.app_name,
    version=settings.app_version,
)

app.include_router(health_router)
app.include_router(alpha_campaign_router)
app.include_router(authority_router)
app.include_router(causal_pipelines_router)
app.include_router(calibrations_router)
app.include_router(autonomous_research_router)
app.include_router(corpus_router)
app.include_router(corpus_sync_router)
app.include_router(curriculum_router)
app.include_router(derived_state_router)
app.include_router(falsification_router)
app.include_router(ingestion_router)
app.include_router(intelligence_evaluation_router)
app.include_router(discovery_router)
app.include_router(discovery_portfolio_router)
app.include_router(laboratory_router)
app.include_router(lake_operations_router)
app.include_router(ingestion_recovery_router)
app.include_router(institutional_lifecycle_router)
app.include_router(lifecycle_router)
app.include_router(market_data_catalog_router)
app.include_router(evaluator_routing_router)
app.include_router(lifecycle_consequence_router)
app.include_router(metrics_router)
app.include_router(model_evaluations_router)
app.include_router(memory_router)
app.include_router(missions_router)
app.include_router(operational_notes_router)
app.include_router(operations_router)
app.include_router(observability_router)
app.include_router(oms_schemas_router)
app.include_router(offline_rl_router)
app.include_router(off_policy_router)
app.include_router(risk_stress_router)
app.include_router(risk_rules_router)
app.include_router(risk_budget_schemas_router)
app.include_router(packages_router)
app.include_router(platform_router)
app.include_router(portfolio_solvers_router)
app.include_router(portfolio_capacity_schemas_router)
app.include_router(execution_calibration_schemas_router)
app.include_router(execution_event_schemas_router)
app.include_router(microstructure_models_router)
app.include_router(prompt_policies_router)
app.include_router(agent_packages_router)
app.include_router(agent_proposals_router)
app.include_router(agents_router)
app.include_router(controls_router)
app.include_router(conversations_router)
app.include_router(channel_conversations_router)
app.include_router(data_contracts_router)
app.include_router(evidence_router)
app.include_router(factor_language_router)
app.include_router(fleet_router)
app.include_router(founder_channel_router)
app.include_router(governance_router)
app.include_router(governance_audit_router)
app.include_router(graph_router)
app.include_router(agent_runtime_router)
app.include_router(agent_fleet_router)
app.include_router(agent_governance_router)
app.include_router(agent_context_router)
app.include_router(agent_context_runtime_router)
app.include_router(agent_research_router)
app.include_router(agent_notes_router)
app.include_router(tasks_router)
app.include_router(venue_identities_router)
app.include_router(proposals_router)
app.include_router(quantitative_receipts_router)
app.include_router(reference_data_router)
app.include_router(research_router)
app.include_router(research_bridge_router)
app.include_router(retrieval_router)
app.include_router(research_programs_router)
app.include_router(runbook_packages_router)
app.include_router(selection_audit_router)
app.include_router(scientific_fidelity_router)
app.include_router(statistical_search_router)
app.include_router(task_runtime_router)
app.include_router(task_graphs_router)
app.include_router(supervisor_router)
app.include_router(symbolic_search_router)
app.include_router(surveillance_router)
app.include_router(workload_identities_router)
