from fastapi import FastAPI

from app.api.routes import (
    agent_context_router,
    agent_context_runtime_router,
    agent_fleet_router,
    agent_governance_router,
    agent_notes_router,
    agent_packages_router,
    agent_proposals_router,
    agent_research_router,
    agent_runtime_router,
    agents_router,
    authority_router,
    channel_conversations_router,
    controls_router,
    conversations_router,
    corpus_router,
    corpus_sync_router,
    curriculum_router,
    data_contracts_router,
    evidence_router,
    fleet_router,
    founder_channel_router,
    governance_audit_router,
    governance_router,
    graph_router,
    health_router,
    ingestion_recovery_router,
    ingestion_router,
    institutional_lifecycle_router,
    laboratory_router,
    lifecycle_consequence_router,
    lifecycle_router,
    memory_router,
    metrics_router,
    missions_router,
    observability_router,
    operational_notes_router,
    operations_router,
    packages_router,
    platform_router,
    proposals_router,
    research_bridge_router,
    research_programs_router,
    research_router,
    retrieval_router,
    runbook_packages_router,
    supervisor_router,
    surveillance_router,
    task_graphs_router,
    task_runtime_router,
    tasks_router,
    workload_identities_router,
)
from app.core.config import get_settings

settings = get_settings()

app = FastAPI(
    title=settings.app_name,
    version=settings.app_version,
)

app.include_router(health_router)
app.include_router(authority_router)
app.include_router(corpus_router)
app.include_router(corpus_sync_router)
app.include_router(curriculum_router)
app.include_router(ingestion_router)
app.include_router(laboratory_router)
app.include_router(ingestion_recovery_router)
app.include_router(institutional_lifecycle_router)
app.include_router(lifecycle_router)
app.include_router(lifecycle_consequence_router)
app.include_router(metrics_router)
app.include_router(memory_router)
app.include_router(missions_router)
app.include_router(operational_notes_router)
app.include_router(operations_router)
app.include_router(observability_router)
app.include_router(packages_router)
app.include_router(platform_router)
app.include_router(agent_packages_router)
app.include_router(agent_proposals_router)
app.include_router(agents_router)
app.include_router(controls_router)
app.include_router(conversations_router)
app.include_router(channel_conversations_router)
app.include_router(data_contracts_router)
app.include_router(evidence_router)
app.include_router(fleet_router)
app.include_router(founder_channel_router)
app.include_router(governance_router)
app.include_router(governance_audit_router)
app.include_router(graph_router)
app.include_router(agent_runtime_router)
app.include_router(agent_fleet_router)
app.include_router(agent_governance_router)
app.include_router(agent_context_router)
app.include_router(agent_context_runtime_router)
app.include_router(agent_research_router)
app.include_router(agent_notes_router)
app.include_router(tasks_router)
app.include_router(proposals_router)
app.include_router(research_router)
app.include_router(research_bridge_router)
app.include_router(retrieval_router)
app.include_router(research_programs_router)
app.include_router(runbook_packages_router)
app.include_router(task_runtime_router)
app.include_router(task_graphs_router)
app.include_router(supervisor_router)
app.include_router(surveillance_router)
app.include_router(workload_identities_router)
